version: '1'
services:
  application:
    image: 'zlemyztex/prometheus-springboot-monitoring:0.1'
    ports:
      - 8080:8080
  prometheus:
    image: 'prom/prometheus:latest'
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: 'grafana/grafana:latest'
    volumes:
      - ./configs/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  postgresql:
    image: 'postgres'
    ports:
      - 5432:5432