management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: [ 0.99, 0.95, 0.90 ]
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"