management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      maximum-expected-value:
        http.server.requests: 5s
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"