apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'spring'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'spring-app:8080' ]
            labels:
              application: 'springboot-example'