global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'application:8080' ]
        labels:
          application: 'springboot-example'